name: Python Release

on:
  push:
    tags:
      - python-v*

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN_DIST }}
  DIST_DIR: ${{ github.sha }}

jobs:

  create_wheels_manylinux:
    runs-on: ubuntu-latest
    name: Create wheels for manylinux2010
    container: quay.io/pypa/manylinux2010_x86_64@sha256:d02389c35c7e9b6c51a21d71e9e98e6fd57c1225f7a782b3965d5a1e1b3585d4
    steps:
      # v1 is required when using manylinux2010
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yum install -y openssl-devel

      - name: Build and audit wheels
        working-directory: ./bindings/python
        run: sh build-wheels.sh

      - name: Upload wheels
        uses: actions/upload-artifact@v1
        with:
          name: wheels
          working-directory: ./bindings/python
          path: ./dist


